# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60)),
                ('user_location', models.CharField(default=None, max_length=60)),
                ('user_online_status', models.CharField(choices=[('O', 'Online'), ('A', 'Away'), ('B', 'Busy'), ('OF', 'Offline'), ('C', 'Custom')], default='A', max_length=200)),
                ('user_post_status', models.CharField(default=None, max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
